### ISSUE TITLE
after going through the steps, I get "Incorrect padding"

### ISSUE THREAD

**Issue by mcurti** [anilkyelam/mendeley-rmsync#1]
`Traceback (most recent call last):                                                                                                                                 File "sync.py", line 348, in <module>                                                                                                                              main()                                                                                                                                                         File "sync.py", line 246, in main                                                                                                                                  session = get_session()                                                                                                                                        File "sync.py", line 122, in get_session                                                                                                                           mendeley_token = json.loads(base64.b64decode(mendeley_token_b64.encode()).decode())                                                                            File "/usr/lib/python3.8/base64.py", line 87, in b64decode                                                                                                         return binascii.a2b_base64(s)                                                                                                                                binascii.Error: Incorrect padding` 

this is the error I get

**Comment by anilkyelam** [comment]
You may have copied the token incorrectly in the `.mendeley_config` file. For example,  I was able to repro this error by leaving out the first line of the token generated from `mendeley-get-token`. Make sure to copy the token all the way from (and excluding) `MENDELEY_OAUTH2_TOKEN_BASE64=` till the end, with no trailing spaces. 


![Screen Shot 2022-01-28 at 11 03 46 AM](https://user-images.githubusercontent.com/19861675/151607593-75a81602-260c-4be9-bf89-eddf0a60b42d.png)


hope that helps!

**Comment by dschick** [comment]
I added a `=` to the end of my token to solve this issue.
However, I then end up with the #3 issue
