### ISSUE TITLE
syntax error near unexpected token 

### ISSUE THREAD

**Issue by angelagoodwork** [anilkyelam/mendeley-rmsync#2]
Hello everyone
I have encountered an error when I type in the client Id and URL in the terminal. The error is shown in this picture here:
<img width="565" alt="Screenshot 2022-02-04 at 14 45 02" src="https://user-images.githubusercontent.com/99027970/152539215-eb0a65f4-9798-4c7f-9f74-4411bcdd4ae2.png">

The syntax in the terminal is like this:
macdeMacBook-Pro:~ mac$ MENDELEY_CLIENT_ID=<118> MENDELEY_CLIENT_SECRET=<oxOtnlZcRKRejJGY> MENDELEY_REDIRECT_URI=<http://localhost:8888/> mendeley get token
-bash: syntax error near unexpected token `118'

Does anyone know what I did wrong? I followed the steps and first installed the Mendeley-CLI, then in this step I got this error.
Thanks so much for any answer!

**Comment by anilkyelam** [comment]
try it without the angle brackets:
MENDELEY_CLIENT_ID=118 MENDELEY_CLIENT_SECRET="***" MENDELEY_REDIRECT_URI="http://localhost:8888/" mendeley get token
